### PR TITLE
[Renames][ApiBreak]  FigmaSharp.NativeControls to FigmaSharp.Controls

### PR DESCRIPTION
**Pull request by netonjm**
We change namespace from FigmaSharp.NativeControls to FigmaSharp.Controls
cc @hbons and @nmilcoff

### CODE REVIEW

**Comment by netonjm** [comment]
Good catch! but it seems this Converters were dropped from the project when we moved to the new components, probably I think it's because there are no component yet, no @hbons  ?

image

**Comment by hbons** [comment]
I don't have any memory of these converters. :)

**Comment by netonjm** [comment]
Then probably are here from ages, @hbons could you please take a look and check if there is something missing? if not we can remove it

**Comment by hbons** [comment]
You can remove them. If we decide we need these later we can always add them back.

**Pull request merged**
