### PR TITLE
extension: Add new solution pad folder icon

### PR DESCRIPTION
**Pull request by hbons**
- [x] New folder icon
- [ ] Integrate icon

### CODE REVIEW

**Comment by hbons** [comment]
image

@netonjm can you hook up the new folder icon please? I don't know what I'm doing wrong...

**Comment by netonjm** [comment]
is this icon implemented?

**Comment by hbons** [comment]
@netonjm yea, see the commits.

**Comment by netonjm** [comment]
Fixed 
image

**Pull request merged**
